# name: Deploy TimeTrack

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Check out repository
#         uses: actions/checkout@v3

#       - name: Set up Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: "20"

#       - name: Install dependencies
#         run: |
#           cd client
#           npm install
#           cd ../server
#           npm install

#       - name: Build client
#         run: |
#           cd client
#           npm run build

#       - name: Deploy to Vercel
#         run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
